spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/inventrydbs?createDatabaseIfNotExist=true
    username: root
    password: 
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  show-sql: true
 
server:
  port: 8080